### PR TITLE
Added the update_field method to boxes

### PR DESCRIPTION
**Pull request by chooserich**
This enables you to update the field value for a specific box.

### CODE REVIEW

**Comment by jsboulanger** [comment]
@biznickman is this syntactic sugar for Streak::FieldValue.update ? It seems to be calling the same API endpoint.

**Comment by chooserich** [comment]
@jsboulanger umm wow, did not see that one only looked at the field class. Sorry about that!

**Comment by jsboulanger** [comment]
@biznickman it's indeed not super obvious, a method in Box that delegates to the update method on FieldValue could helpful.

**Comment by chooserich** [comment]
@jsboulanger I guess I could make the method an alias.

**Pull request closed without merging**
